### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by hackerzyh** [fxtxkktv/lnmDNS#5]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/lnmDNS/tools/Login.py", line 28, in BtnPrv
    return fn(*args,**kw)
  File "/opt/lnmDNS/tools/System.py", line 491, in syscheck
    result = cmds.envCheck()
  File "Functions.py", line 154, in Functions.cmdhandle.envCheck
TypeError: envCheck() takes exactly 2 positional arguments (1 given)

这个错误我应该如何处理，麻烦回复一下

**Comment by fxtxkktv** [comment]
envCheck是用于核对os相关的组件是否安装完整，这个页面正常应该不影响使用，也可以直接在System.py里面把cmds.envCheck()方法屏蔽
不知道你这边是怎么触发这个问题的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fxtxkktv/lnmDNS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 下午5:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fxtxkktv/lnmDNS] 错误 (Issue #5)





 
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
 return route.call(**args)
 File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
 rv = callback(*a, **ka)
 File "/opt/lnmDNS/tools/Login.py", line 28, in BtnPrv
 return fn(*args,**kw)
 File "/opt/lnmDNS/tools/System.py", line 491, in syscheck
 result = cmds.envCheck()
 File "Functions.py", line 154, in Functions.cmdhandle.envCheck
 TypeError: envCheck() takes exactly 2 positional arguments (1 given)
 
这个错误我应该如何处理，麻烦回复一下

**Comment by hackerzyh** [comment]
是的，不影响使用，只是看到一个 感叹号"!" 就想消灭掉
